name: carriage_rider
description: Carriage Rider App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_sign_in: ^4.4.4
  http: ^0.13.0
  intl: ^0.16.1
  provider: ^4.0.5+1
  url_launcher:
  image_picker: ^0.7.0
  flutter_datetime_picker: ^1.4.0
  flutter_typeahead: ^1.8.8
  flutter_verification_code: ^0.2.1
  jwt_decoder: ^1.0.4
  flutter_secure_storage: ^3.3.5
  flutter_svg: ^0.22.0
  pull_to_refresh: 1.6.3
  custom_refresh_indicator: ^0.9.0
  overlay_support:
  firebase_messaging: ^10.0.8
  firebase_core:
  loading_overlay: ^0.2.1
  flutter_local_notifications:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Black.ttf
          weight: 900
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter-Thin.ttf
          weight: 200
        - asset: fonts/Inter-ExtraLight.ttf
          weight: 100
  assets:
    - assets/images/
    - assets/images/onboard_1/
    - assets/images/onboard_2/
    - assets/images/onboard_3/
    - assets/images/onboard_4/

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/logo_rider.png"
  image_path_android: "assets/images/logo_rider.png"
