name: CI Build
on: pull_request

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "8.x"
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.2.3"
      - name: Get
        run: flutter pub get
      - name: Build
        run: flutter build apk
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "8.x"
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.2.3"
      - name: Get
        run: flutter pub get
      - name: Build
        run: flutter build ios
